#!/bin/sh

NREPS="$1"
shift

if [ -z "$NREPS" ]; then
    echo "Usage: ./compose.sh <nreps>"
    exit 1
fi

OLD=$(docker-compose config --services | wc -l)

if [ "$NREPS" = "$OLD" ]; then
    echo "Config file good"
else
    docker-compose down

    cat <<EOF >docker-compose.yml
# DO NOT EDIT: Automatically generated by compose.sh
version: "2.3"
services:
EOF

    I=0
    while [ "$I" -lt "$NREPS" ]; do
        cat <<EOF >>docker-compose.yml

  epaxos-server-$I:
    image: b1f6c1c4/epaxos
    container_name: epaxos-server-$I
    restart: always
    environment:
      EPAXOS_LISTEN: "0.0.0.0:23333"
      EPAXOS_NREPLICAS: "$NREPS"
      EPAXOS_REPLICA_ID: "$I"
      EPAXOS_SERVERS_FMT_BIAS: "0"
      EPAXOS_SERVERS_FMT: "epaxos-server-%d"
    ports:
      - "$((23333+$I)):23333"
    volumes:
      - ./data-$I/data/epaxos
    networks:
      - epaxos
EOF
    I=$(($I+1))
    done

    cat <<EOF >>docker-compose.yml

networks:
  epaxos:
    driver: bridge
EOF

    echo "Config file regenerated"
fi

if [ ! "$#" = 0 ]; then
    docker-compose "$@"
fi
