.PHONY: report

.SECONDARY:

report/%.csv: scripts/%.sh scripts/setup.sh scripts/teardown.sh
	mkdir -p report/
	$< | tee $@ >/dev/null

report/%.pdf: scripts/%.R report/%.csv
	Rscript --vanilla $< || rm -f $@

report: report/plot1.pdf report/plot2.pdf report/plot3.pdf
