.PHONY: report

.SECONDARY:

report/%.csv: scripts/%.sh scripts/setup.sh scripts/teardown.sh
	mkdir -p report/
	$< | tee $@ >/dev/null

report/%.png: scripts/%.R report/%.csv
	Rscript --vanilla $< || rm -f $@

report: report/plot1.png report/plot2.png report/plot3.png
