apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: epaxos
  labels:
    app: epaxos
spec:
  serviceName: epaxos
  replicas: 3
  selector:
    matchLabels:
      app: epaxos
  template:
    metadata:
      labels:
        app: epaxos
    spec:
      terminationGracePeriodSeconds: 3
      containers:
      - name: epaxos
        image: b1f6c1c4/epaxos:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 23330
          name: server-server
          protocol: UDP
        - containerPort: 23330
          name: client-server
          protocol: TCP
        # resources:
        #   limits:
        #     cpu: "500m"
        #     memory: 1Gi
        #   requests:
        #     cpu: "500m"
        #     memory: 1Gi
        # securityContext:
        #   capabilities:
        #     add:
        #       - IPC_LOCK
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "export EPAXOS_REPLICA_ID=${HOSTNAME##*-}"]
        env:
          - name: EPAXOS_DEBUG
            value: "FALSE"
          - name: EPAXOS_LISTEN
            value: "0.0.0.0:23330"
          - name: EPAXOS_NREPLICAS
            valueFrom:
              fieldRef:
                fieldPath: spec.replicas
          - name: EPAXOS_SERVERS_FMT_BIAS
            value: "0"
          - name: EPAXOS_SERVERS_FMT
            value: "epaxos-%d.epaxos.default.svc.cluster.local:23330"
          - name: EPAXOS_DATA_PREFIX
            value: "/data/epaxos/data-"
        # readinessProbe:
        #   exec:
        #     command:
        #     - /go/bin/ready-probe
        #   initialDelaySeconds: 5
        #   timeoutSeconds: 3
        # These volume mounts are persistent. They are like inline claims,
        # but not exactly because the names need to match exactly one of
        # the stateful pod volumes.
        volumeMounts:
        - name: epaxos-data
          mountPath: /data/epaxos
  # These are converted to volume claims by the controller
  # and mounted at the paths mentioned above.
  # do not use these in production until ssd GCEPersistentDisk or other ssd pd
  volumeClaimTemplates:
  - metadata:
      name: epaxos-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: fast
      resources:
        requests:
          storage: 1Gi
